#!/usr/bin/env bash

# ipnfo
# Show ip and location information for the specified user
# if no parameter is specified then show ipinfo for logged user.

# USAGE
# ipinfo
# ipinfo [username]

if [ "$1" ]; then
        sudo -u "$1" -i -- curl -s ipinfo.io | \
        awk 'NR == 2 { gsub("\"","") gsub(",",""); printf $2 ":" } \
        NR == 6 { gsub("\"","") gsub(",",""); print $2 }'
else
        curl -s ipinfo.io | \
        awk 'NR == 2 { gsub("\"","") gsub(",",""); printf $2 ":" } \
        NR == 6 { gsub("\"","") gsub(",",""); print $2 }'
fi
